apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-loop-deployment
  labels:
    app: crash-loop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-loop
  template:
    metadata:
      labels:
        app: crash-loop
    spec:
      containers:
      - name: crash-loop
        image: dontspamterry/crash-loop:latest

